Algoritmo "4C"
// Disciplina  : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros (1+2+3+4+...+98+99+100).
// Autor(a)    : Vitória Fernandes
// Data atual  : 11/09/2021

Var
cont, soma : Inteiro

Inicio
cont<-0
Para cont de 1 ate 100 passo 1 faca
soma<-soma+cont
FimPara
Escreval ("O valor da soma de todos os números de 1 - 100 é: ", soma)

Fimalgoritmo