Algoritmo "Antecessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vitória Fernandes
// Data atual  : 25/08/2021
Var
antecessor,numero:Inteiro

Inicio
Escreval("Digite um número")
Leia(numero)
antecessor:=numero-1
Escreval ("O antecessor do numero é:",antecessor)

Fimalgoritmo