Algoritmo "Sucessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Algorítmo que mostra o sucessor de um número dado
// Autor(a)    : Vitória Fernandes
// Data atual  : 25/08/2021
Var
sucessor,numero:Inteiro

Inicio
Escreval("Digite um número")
Leia(numero)
Sucessor :=numero-1
Escreval ("o sucessor do numero é  :",sucessor)


Fimalgoritmo