Algoritmo "3C"
// Disciplina  : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Elaborar um programa que apresente no final o somatório dos valores pares existentes na faixa de 1 até 500.
// Autor(a)    : Vitória Fernandes
// Data atual  : 06/09/2021

Var
par, soma:inteiro

Inicio
soma<-0
enquanto par<500 faca
par<-par+2
soma<-soma+par
fimenquanto

Escreval("O valor da soma dos números pares é ",soma )

Fimalgoritmo