Algoritmo "15"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler um valor e escrever se é positivo ou negativo (considere o valor zero como positivo).
// Autor(a)    : Vitória Fernandes
// Data atual  : 30/08/2021
Var
numero : Real

Inicio
Escreva ("Digite um número: ")
Leia (numero)
Se numero >= 0 entao
Escreval ("O número é positivo")
Senao
Escreval ("O número é negativo")
FimSe

Fimalgoritmo