Algoritmo "39"
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição : Para A = V, B = V e C = F, qual o resultado da avaliação das seguintes expressões: a) (A e B) ou (A ou B) b) (A ou B) e (A e C) c) A ou C e B ou A e não B
// Autor(a) : Vitória Fernandes
// Data atual : 02/09/2021

Var

Inicio
a) (A e B) ou (A ou B)
b) (A ou B) e (A e C)
c) A ou C e B ou A e não B
Fimalgoritmo